### PR TITLE
Blog App - processing data in models

### PR DESCRIPTION
**Pull request by basitali111**
- Set up associations between models.
- Write SQL queries with Active Record.

### CODE REVIEW

**Review by AmaduKamara — CHANGES_REQUESTED** [review]
# Status: Required Changes ♻️♻️♻️ 

Hi @basitali111,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly 👍 
✅ Linter checks passed 👍 
✅ Created models and associations as required 👍 

## Required Changes ♻️
_Check the comments under the review._

Everything else is great 👍. BUT:

- [ ] Kindly document your project in a professional way as you have been doing with all your previous projects using the Microverse Professional README Template and have all contents relating to the current project you are working on - Blog App👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by basitali111** [comment]
> # Status: Required Changes ♻️♻️♻️
> Hi @basitali111,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> ✅ You used Gitflow correctly 👍 ✅ Linter checks passed 👍 ✅ Created models and associations as required 👍
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> Everything else is great 👍. BUT:
> 
> * [ ]  Kindly document your project in a professional way as you have been doing with all your previous projects using the Microverse Professional README Template and have all contents relating to the current project you are working on - Blog App👍
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

thanks for pointing i just forgot to add

**Comment by basitali111** [comment]
thanks for pointing i just forgot to add

**Review by elmar8287 — APPROVED** [review]
Hi, @basitali111.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

### Highlights

- Good README file 👍 

### Optional suggestions

- Please, consider fixing the broken link to the MIT.md file
- Please, in the future consider the Github flow: branch should have the name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section') 👍 In your case it is `developer` and does not cover Github glow - doing this you will increase your professional skills while working in Github 🥇 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
giphy

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
